### ISSUE TITLE
Write access needed to master for me

### ISSUE THREAD

**Issue by pythonsavvy** [UWPCE-PythonCert-ClassRepos/PythonCert220Assign#2]
Please can someone grant - thanks

**Comment by PythonCHB** [comment]
Odd -- not sure how you were able to create the repo, but not be able to push to it.

But I've made you and "owner" of this org, so you should be god to go.

Is this intended to be a template for the 220 classes?, or one for a particular class? If the latter, then se may want to change the name to include the modality and timeframe: e.g. Winter2019Classroom or something.

Also, you could create a team for this class -- that would be the instructor and TA.

**Comment by pythonsavvy** [comment]
Thanks - I think its cos I got the org wrong originally. This is the student's template for py220 activities and assignments. About to push the content; its been in gitlab. Tis has all the autograding with pytest, linitng and coverage
